version: "3.7"
services:

  # https://hub.docker.com/r/grafana/grafana
  grafana:
    image: grafana/grafana
    ports:
      - "3000"
    network_mode: "host"

  # https://hub.docker.com/r/prom/prometheus
  prometheus:
    image: prom/prometheus
    ports:
      - "9090"
    network_mode: "host"